branches:
    only:
    - master

os:
    - linux

env:
    - PY=3.7

addons:
    apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gfortran
        - libblas-dev
        - liblapack-dev
        - libopenmpi-dev
        - openmpi-bin

install:
- |
    cd ..
    echo ">>> Building python environment";
    echo " >> Installing conda";
    echo "  > Downloading miniconda";
    wget "https://repo.anaconda.com/miniconda/Miniconda${PY:0:1}-latest-Linux-x86_64.sh" -O miniconda.sh;
    chmod +x miniconda.sh;
    echo "  > Installing miniconda";
    ./miniconda.sh -b  -p $HOME/miniconda;
    export PATH=$HOME/miniconda/bin:$PATH;

    echo " >> Creating conda environment";
    conda create --yes -n PY$PY python=$PY;
    source $HOME/miniconda/bin/activate PY$PY;

    echo " >> Installing non-pure Python dependencies from conda";
    conda install --yes numpy=$NUMPY scipy=$SCIPY cython swig matplotlib;

    cd pandemic/;
    ls -ltr;
    chmod 755 ./build_pyoptsparse_ipopt.sh; ./build_pyoptsparse_ipopt.sh;

    pip install --upgrade pip;

- python -m pip install git+https://github.com/OpenMDAO/dymos.git --user;

- python -m pip install git+https://github.com/OpenMDAO/OpenMDAO.git --user;

- python -m pip install git+https://github.com/OpenMDAO/testflo.git --user;

script:
    - pwd;
    - ls -ltr;
    - cd pandemic/;
    - export LD_LIBRARY_PATH=/home/travis/ipopt/lib
    - testflo -n 1 --timeout=120 --show_skipped;